name: ci.yml
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLFLOW_ALLOW_FILE_STORE: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: make install
      - name: Format code
        run: make format
      - name: Lint code
        run: make lint
      - name: Run tests
        run: make test
      - name: Run MLflow Project
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          pip install -r requirements.txt
          mlflow run MLProject --env-manager=local
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
        if: always()
