name: CI Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
      - name: Install, Format, Lint, and Test
        run: make all
      - name: Run MLflow Project
        run: mlflow run MLProject

